In [1]:
from pathlib import Path
from tqdm import tqdm
import pandas as pd
import numpy as np
import matplotlib as matplotlib
import matplotlib.pyplot as plt

from shapely.geometry import Point, Polygon
import geopandas as gpd

/Users/etriesch/dev/forest-biomass-modeling/venv/forest-biomass-modeling/lib/python3.9/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.10.2-CAPI-1.16.0) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(

In [2]:
from utils import DATA_CLEAN_PATH
from utils import GEO_CRS, PROJ_CRS
from utils import set_plt_settings

# And change jupyter settings to auto-reload these functions before each instance running them
%load_ext autoreload
%autoreload 2
set_plt_settings()

In [3]:
k = 'lst'

test = pd.read_csv(DATA_CLEAN_PATH / f'modis_annual_{k}.csv')

In [4]:
test

,lat,lon,year,prop_mean,prop_std,prop_min,prop_max,mbm_sum,dbm_sum,consec_mbm_max
0,24.031675,-110.990415,2000,15405.454545,185.475801,15207.0,15736.0,6,2,3
1,24.031675,-110.990415,2001,15319.666667,198.871056,15062.0,15616.0,5,1,3
2,24.031675,-110.990415,2002,15311.416667,190.713235,15011.0,15551.0,5,1,4
3,24.031675,-110.990415,2003,15340.166667,134.838512,15106.0,15528.0,5,1,4
4,24.031675,-110.990415,2004,15322.666667,209.215997,14950.0,15589.0,5,1,3
...,...,...,...,...,...,...,...,...,...,...
9093678,48.988608,-66.034171,2017,13693.333333,696.248040,12780.0,14543.0,6,1,4
9093679,48.988608,-66.034171,2018,13629.000000,708.066509,12644.0,14681.0,7,1,4
9093680,48.988608,-66.034171,2019,13595.333333,669.568156,12709.0,14538.0,6,1,4
9093681,48.988608,-66.034171,2020,13727.500000,621.765010,12836.0,14677.0,6,1,4
9093682,48.988608,-66.034171,2021,13793.083333,619.643953,12957.0,14601.0,5,1,3